language: generic
sudo: required
services:
    - docker

before_install:
    - gem install bundler
    - ./bin/build.sh -b "apache-debian fpm-alpine" -s "dev prod" -k -c $TRAVIS_BRANCH

script:
  - ./bin/simple-test.sh master
  - ./bin/push.sh master

